Update examples.yml

diff --git a/.github/workflows/examples.yml b/.github/workflows/examples.yml
--- a/.github/workflows/examples.yml
+++ b/.github/workflows/examples.yml
@@ -67,29 +67,6 @@ jobs:
         VERSION=0.11.2
         curl -sSf https://raw.githubusercontent.com/WasmEdge/WasmEdge/master/utils/install.sh | sudo bash -s -- --version=$VERSION -p /usr/local
 
-    - name: MySQL simple examples
-      run: |
-        cd mysql
-        cargo build --target wasm32-wasi --release
-        wasmedgec target/wasm32-wasi/release/query.wasm query.wasm
-        wasmedgec target/wasm32-wasi/release/insert.wasm insert.wasm
-        resp=$(wasmedge --env "DATABASE_URL=mysql://root:root@127.0.0.1:3306/mysql" query.wasm 2>&1)
-        echo "$resp"
-        if [[ $resp == *"localhost"* ]]; then
-          echo -e "Execution Success!"
-        else
-          echo -e "Execution Fail!"
-          # exit 1
-        fi
-        resp=$(wasmedge --env "DATABASE_URL=mysql://root:root@127.0.0.1:3306/mysql" insert.wasm 2>&1)
-        echo "$resp"
-        if [[ $resp == *"foo"* ]]; then
-          echo -e "Execution Success!"
-        else
-          echo -e "Execution Fail!"
-          exit 1
-        fi
-        
     - name: Anna KVS examples
       run: |
         cd anna
@@ -132,3 +109,26 @@ jobs:
           exit 1
         fi
     
+    - name: MySQL simple examples
+      run: |
+        cd mysql
+        cargo build --target wasm32-wasi --release
+        wasmedgec target/wasm32-wasi/release/query.wasm query.wasm
+        wasmedgec target/wasm32-wasi/release/insert.wasm insert.wasm
+        resp=$(wasmedge --env "DATABASE_URL=mysql://root:root@127.0.0.1:3306/mysql" query.wasm 2>&1)
+        echo "$resp"
+        if [[ $resp == *"localhost"* ]]; then
+          echo -e "Execution Success!"
+        else
+          echo -e "Execution Fail!"
+          # exit 1
+        fi
+        resp=$(wasmedge --env "DATABASE_URL=mysql://root:root@127.0.0.1:3306/mysql" insert.wasm 2>&1)
+        echo "$resp"
+        if [[ $resp == *"foo"* ]]; then
+          echo -e "Execution Success!"
+        else
+          echo -e "Execution Fail!"
+          exit 1
+        fi
+        
